### ISSUE TITLE
Redeemable Logic

### ISSUE THREAD

**Issue by joaop21** [cesium/safira#140]
A redeemable is something that an attendee can win (shirt, pen, etc).
It has a maximum of time that can be redeemed, and also a maximum of times that can be redeemed by an attendee.
It is also important to know if a redeemable was already redeemed in the physical world.

**Comment by JoaoSCosta** [comment]
Is it still important to know if a redeemable has already been withdrawn? @joaop21

**Comment by jpcorreia99** [comment]
Don't think so since we agreed that items are only redeemed at the end of the event, but maybe I'm wrong, what do you say @joaop21

**Comment by joaop21** [comment]
It's not important, as @jpcorreia99 said.
