### ISSUE TITLE
Roulette

### ISSUE THREAD

**Issue by joaop21** [cesium/safira#166]
When a participant has already won the maximum allowed prize that is possible for a participant to win, and that prize comes up again on a roulette spin, what should we do? A new spin?

**Comment by jpcorreia99** [comment]
Since we allow it for someone to win nothing, I think the most sensible choice would be to spin it again.

**Comment by joaop21** [comment]
There may come a time when the participant is unable to win anything at roulette, and so the roulette becomes a token pit.

**Comment by jpcorreia99** [comment]
Given the amount of prizes and the small probability of some of them, I would say that if something like that were to happen (which I don't even know if it would actually happen in a 4 day event) it would only happen at the end of the last day, no?

**Comment by miguelbrandao** [comment]
I agree with what @jpcorreia99 said
