### ISSUE TITLE
Daily Leaderboard

### ISSUE THREAD

**Issue by joaop21** [cesium/safira#167]
For the daily leaderboard, should we break the tie with the number of tokens the participant has earned in total, or with the number of tokens they have in their balance?

**Comment by jpcorreia99** [comment]
Using their current balance would make it more interesting.

**Comment by joaop21** [comment]
Yes, I agree. Because we can assume that the participant with smaller token balance, has already bought more things in the store, or has won more prizes int the roulette, which in itself causes more expense to the event. So whoever has a higher balance should come out ahead in case of a tie.

**Comment by miguelbrandao** [comment]
Exactly, balance is the way.
