### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by miguelbrandao** [cesium/safira#226]
Updating multiple dependencies like in #225 has a high risk of breaking something.

We should have decent test coverage so we can run them automatically on PRs. Maybe this could be incorporated with the Postman documentation?

**Comment by nelsonmestevao** [comment]
Postman would be really cool to have a better development experience and documentation for the frontend team.

 However, for testing is still a bit tedious, there's not yet a good solution to reuse functions and code between multiple endpoints. Also, it requires npm to automatically run the tests. I think ExUnit it's a clean and more efficient way to test elixir applications.

**Comment by ruioliveira02** [comment]
This has been done :muscle:
