### ISSUE TITLE
Login error returned when registering with errors

### ISSUE THREAD

**Issue by Mendess2526** [cesium/safira#37]
Whenever a register request is sent that contains any of the documented errors this is returned:
  ```json
    {
      "error": "Login error"
    }
  ```
instead of the [documented error responses](https://github.com/cesium/safira/blob/master/README.md#errors).

**Comment by 0urobor0s** [comment]
Check #39 and give feedback

**Comment by Mendess2526** [comment]
works

**Comment by 0urobor0s** [comment]
Ok, so #39 closes this.
