### ISSUE TITLE
Claimed and Secret Badges

### ISSUE THREAD

**Issue by apedrob** [cesium/safira#42]
> _Nam in porta lorem. Maecenas eget lorem pharetra, venenatis odio eget, suscipit augue. In convallis placerat lectus, sit amet mattis erat pulvinar vel. Duis in nulla ut risus facilisis dictum quis sit amet arcu. Vivamus eget dapibus odio, ac pretium nunc. Aenean nec leo arcu. Phasellus sit amet nibh nec velit ultricies mollis. Sed ut tempor sem. Aliquam volutpat arcu a quam lobortis, at dictum tortor facilisis._

**Comment by ZePedroResende** [comment]
Implemented on (#66 and #67)
